server:
  port: 8081

mysql:
  user:
  pass:
  database:
  host:

environment:
  jenkins:
  octopus:
  repository:

branches:
  pattern: release
  last: 2
  jobs:
    - dependency X
    - dependency Y

caching:
  branchMenu: 180
  builds: 15
