server:
  port: 8081

mysql:
  user:
  pass:
  database:
  host:

environment:
  jenkins:
  octopus:
  repository:

branches:
  pattern: release
  last: 2

table:
  timeoutHours: 2
  branches:
    paging: 20


caching:
  branchMenu: 180
  builds: 15
